import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default function getStyles(isDarkMode) {

    const backgroundColor = isDarkMode ? '#1A1A1A' : '#FFFFFF';
    const cardBackground = isDarkMode ? '#2D2D2D' : '#FFFFFF';
    const textColor = isDarkMode ? "#FFFFFF" : "#131F3C";
    const secondaryTextColor = isDarkMode ? "#CCCCCC" : "#666666";
    const borderColor = isDarkMode ? "#444" : "#E0E0E0";
    const primaryColor = '#856bccff';

    return StyleSheet.create({
        navbar: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingTop: 50,
            paddingBottom: 15,
            backgroundColor: 'transparent',
        },
        fotoContainer: {
            width: 50,
            height: 50,
            borderRadius: 25,
            overflow: 'hidden',
        },
        fotoPerfil: {
            width: '100%',
            height: '100%',
            borderRadius: 25,
        },
        menuButton: {
            padding: 5,
        },
        menuDropdown: {
            position: 'absolute',
            top: 110,
            right: 20,
            backgroundColor: 'rgba(45, 27, 105, 0.95)',
            borderRadius: 12,
            padding: 10,
            zIndex: 1000,
            minWidth: 180,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.3,
            shadowRadius: 10,
            elevation: 5,
        },
        menuItem: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 12,
            paddingHorizontal: 15,
            borderRadius: 8,
        },
        menuItemText: {
            color: '#FFFFFF',
            fontSize: 16,
            marginLeft: 10,
            fontWeight: '500',
        },
        scrollContent: {
            flexGrow: 1,
        },
        container: {
            flex: 1,
            backgroundColor: isDarkMode ? '#1A1A1A' : '#FFFFFF',
            borderTopLeftRadius: 40,
            borderTopRightRadius: 40,
            paddingHorizontal: 20,
            paddingTop: 30,
            paddingBottom: 40,
            marginTop: 10,
        },
        header: {
            alignItems: 'center',
            marginBottom: 30,
        },
        titulo: {
            fontSize: 28,
            fontWeight: '700',
            color: textColor,
            textAlign: 'center',
            marginBottom: 8,
        },
        subtitle: {
            fontSize: 16,
            color: secondaryTextColor,
            textAlign: 'center',
        },
        gradeContainer: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
            marginBottom: 30,
        },
        botaoGrade: {
            width: '48%',
            height: height * 0.12,
            marginBottom: 15,
            borderRadius: 20,
            overflow: 'hidden',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 6,
        },
        ultimaLinha: {
            marginBottom: 0,
        },
        botaoGradient: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection: 'column',
            padding: 15,
        },
        botaoIcone: {
            marginBottom: 8,
        },
        botaoTexto: {
            color: '#FFFFFF',
            fontSize: 17,
            fontWeight: '600',
            textAlign: 'center',
        },
        secaoRapida: {
            marginTop: 20,
        },
        secaoTitulo: {
            fontSize: 20,
            fontWeight: '700',
            color: textColor,
            marginBottom: 15,
        },
        botoesRapidos: {
            flexDirection: 'row',
            justifyContent: 'space-between',
        },
        botaoRapido: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDarkMode ? '#2D2D2D' : '#F0F0F0',
            paddingVertical: 12,
            paddingHorizontal: 20,
            borderRadius: 12,
            flex: 0.48,
            justifyContent: 'center',
        },
        botaoRapidoTexto: {
            color: textColor,
            fontSize: 14,
            fontWeight: '600',
            marginLeft: 8,
        },
        // Adicione estas styles ao seu arquivo de estilos existente
        navbar: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingTop: 50,
            paddingBottom: 15,
            backgroundColor: 'transparent',
        },
        logoContainer: {
            padding: 10,
        },
        logoText: {
            color: '#FFFFFF',
            fontSize: 24,
            fontWeight: 'bold',
        },
        menuButton: {
            padding: 10,
            backgroundColor: 'rgba(255,255,255,0.2)',
            borderRadius: 10,
        },
        menuDropdown: {
            position: 'absolute',
            top: 110,
            right: 20,
            backgroundColor: 'rgba(30, 41, 59, 0.95)',
            borderRadius: 15,
            padding: 10,
            zIndex: 1000,
            minWidth: 200,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 12,
            elevation: 8,
        },
        menuItem: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 12,
            paddingHorizontal: 15,
            borderRadius: 10,
            marginBottom: 5,
        },
        menuItemText: {
            color: '#FFFFFF',
            fontSize: 16,
            marginLeft: 12,
            fontWeight: '600',
        },
        scrollContent: {
            flexGrow: 1,
            paddingBottom: 20,
        },
        container: {
            flex: 1,
            backgroundColor: isDarkMode ? '#0F172A' : '#FFFFFF',
            borderTopLeftRadius: 40,
            borderTopRightRadius: 40,
            paddingHorizontal: 20,
            paddingTop: 30,
            paddingBottom: 40,
            marginTop: 10,
        },
        header: {
            alignItems: 'center',
            marginBottom: 30,
        },
        titulo: {
            fontSize: 32,
            fontWeight: '800',
            color: textColor,
            textAlign: 'center',
            marginBottom: 8,
        },
        subtitle: {
            fontSize: 18,
            color: secondaryTextColor,
            textAlign: 'center',
            fontWeight: '500',
        },
        gradeContainer: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
            marginBottom: 30,
        },
        botaoGrade: {
            width: '48%',
            height: 120,
            marginBottom: 15,
            borderRadius: 20,
            overflow: 'hidden',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 6 },
            shadowOpacity: 0.3,
            shadowRadius: 12,
            elevation: 8,
        },
        botaoGradient: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            padding: 15,
        },
        botaoTexto: {
            color: '#FFFFFF',
            fontSize: 14,
            fontWeight: '700',
            textAlign: 'center',
            marginTop: 8,
            textShadowColor: 'rgba(0, 0, 0, 0.3)',
            textShadowOffset: { width: 1, height: 1 },
            textShadowRadius: 2,
        },
        metasContainer: {
            backgroundColor: isDarkMode ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
            padding: 20,
            borderRadius: 20,
            marginBottom: 20,
        },
        metasTitulo: {
            fontSize: 20,
            fontWeight: '700',
            color: textColor,
            marginBottom: 15,
            textAlign: 'center',
        },
        metasGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
        },
        metaItem: {
            width: '48%',
            alignItems: 'center',
            padding: 12,
            backgroundColor: isDarkMode ? 'rgba(255,255,255,0.05)' : 'rgba(255,255,255,0.8)',
            borderRadius: 15,
            marginBottom: 10,
        },
        metaIcon: {
            width: 40,
            height: 40,
            borderRadius: 20,
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 8,
        },
        metaTexto: {
            fontSize: 14,
            color: textColor,
            fontWeight: '600',
            marginBottom: 4,
        },
        metaStatus: {
            fontSize: 12,
            color: secondaryTextColor,
            fontWeight: '500',
        },
        dicaContainer: {
            backgroundColor: isDarkMode ? 'rgba(245, 158, 11, 0.1)' : 'rgba(245, 158, 11, 0.1)',
            padding: 20,
            borderRadius: 20,
            borderLeftWidth: 4,
            borderLeftColor: '#F59E0B',
        },
        dicaHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 10,
        },
        dicaTitulo: {
            fontSize: 18,
            fontWeight: '700',
            color: textColor,
            marginLeft: 8,
        },
        dicaTexto: {
            fontSize: 14,
            color: textColor,
            lineHeight: 20,
            fontWeight: '500',
        },
        recarregarBotao: {
            marginLeft: 'auto',
            padding: 5,
        },
        recarregando: {
            transform: [{ rotate: '360deg' }],
        },
    });
}